#!/bin/sh
# TO BE USED IN DEVELOPMENT ONLY!
# USE DIFFERENT KEYS IN PROD!!!
export TWITTER_CONSUMER_KEY='KpehfidwlgPOxndJra2h0xO7n'
export TWITTER_CONSUMER_SECRET='k2Eqz2P4CZawy9X36Ep60AtYTe4k191LHDbR88yX8WVfoqXZQU'
node server.js
